.Dd
.Dt FSV 8
.Os
.\"
.\"
.Sh NAME
.Nm fsv
.Nd a process supervisor
.\"
.\"
.Sh SYNOPSIS
.Nm
.Op Fl hqvV
.Op Fl m Ar mask
.Op Fl n Ar name
.Op Fl r Ar recent_restarts_max
.Op Fl S Ar recent_secs
.Op Fl t Ar timeout
.Op Fl l Ar log
.Ar cmd
.Nm
.Op ...
.Fl c Ar cmd
.Nm
.Fl s Ar name
.\"
.\"
.Sh DESCRIPTION
.Nm
is a process supervisor.
It is able to:
.Bl -bullet -width 1n -offset Ds
.It
Run a command
.Va cmd ,
restarting it if it exits for any reason.
.It
Optionally run another
.Va log
process to reliably log messages,
even if either process is restarted.
.It
Maintain state information for all processes managed by
.Nm .
.El
.\"
.\" recent_restarts
.\"
.Pp
.Nm
has a concept of
.Va recent_restarts
for the
.Va cmd
and
.Va log
processes.
.Va recent_restarts
starts at 0 and will increment by 1 every time the process is restarted, unless
.Va recent_secs
or more seconds have passed.
In this case, the event is considered the start of a new string of crashes and
.Va recent_restarts
is set to 1.
.Pp
A maximum number of recent restarts can be set with
.Va recent_restarts_max .
In the event that this number is reached,
.Nm
will take action according to
.Va timeout .
If
.Va timeout
is non-zero,
.Nm
will wait
.Va timeout
seconds before restarting the process again.
If
.Va timeout
is zero,
.Nm
will
.Dq give up
and exit.
.Pp
.Va timeout
is always zero for the
.Va log
process.
This is because it is a very
.Em bad
thing if the log process starts crashing \(em
the pipe will fill up and
.Xr write 2
calls will start blocking when the
.Va cmd
process tries to log.
.\"
.\" options
.\"
.Pp
The options are as follows:
.Pp
.Bl -tag -width Ds
.It Fl c Ar cmd
Alternate way of specifying
.Ar cmd .
.It Fl h , Fl -help
Print a brief help message.
.It Fl l Ar log
Program to pipe
the output of
.Va cmd
into.
.It Fl m Ar mask
Used to specify what output to redirect from
.Va cmd
to
.Va log :
.Dv stdout Pq 1 ,
.Dv stderr Pq 2 ,
or
.Dv both Pq 3 .
Default is 3.
.It Fl n Ar name
Use
.Ar name
as the
.Va cmdname
instead of letting
.Nm
choose it automatically.
.It Fl q
Quiet.
.It Fl r Ar recent_restarts_max
Set
.Va recent_restarts_max
for
.Va cmd .
Prefix the number with
.Ql l
to set for
.Va log
instead.
.It Fl s Ar name
Status.
.It Fl S Ar recent_secs
Set
.Va recent_secs
for
.Va cmd .
Prefix the number with
.Ql l
fo set for
.Va log
instead.
.It Fl t Ar timeout
Set
.Va timeout
for
.Va log .
.It Fl v
Verbose.
.It Fl V , Fl -version
Print version and exit.
.El
.\"
.\"
.Sh FILES
.Nm
keeps its state information in a file tree rooted at
.Dv FSV_CMDDIR_PREFIX ,
by default
.Pa /var/tmp .
This is configurable as a compile-time preprocessor constant
and should be a
.Dq sticky
directory
.Po
If you don't know what this means, see
.Xr chmod 1
.Pc .
.Pp
Under
.Dv FSV_CMDDIR_PREFIX
is a unique
.Va fsvdir
for each user.
Their names are of the format
.Pa fsv-UID ,
where
.Ql UID
is an integer as returned by
.Xr geteuid 2 .
.Pp
Within each
.Va fsvdir
lie the
.Va cmddir
directories which are named after the
.Va cmdname
of each process.
.\"
.\"
.Sh EXIT STATUS
.Nm
makes use of the exit values defined in
.In sysexits.h .
.\"
.\"
.Sh EXAMPLES
Run
.Xr ls 1
as the
.Va cmd .
.Dl $ fsv ls -al
.\"
.\"
.Sh PREPROCESSOR CONSTANTS
.Nm
uses the following preprocessor constants for compile-time configuration:
.Bl -tag -width Ds
.It Dv FSV_CMDDIR_PREFIX
See
.Sx FILES .
.It Dv FSV_DATETIME_FMT
A
.Xr strftime 3
format specification used to display the local date and time.
.El
.\"
.\"
.Sh SEE ALSO
.\"
.\"
.Sh HISTORY
.\"
.\"
.Sh CAVEATS
.Nm
will
.Xr chdir 2
to a specific directory before executing
.Va cmd
and
.Va log ,
so using relative paths to a program
.Pq Pa ./foo , Pa foo/bar
will not work as expected.
Use an absolute path
.Pq Pa /usr/local/bin/foo
instead.
